### PR TITLE
Oommf version 2.0a3

### PR DESCRIPTION
**Pull request by lang-m**
- Update to OOMMF 2.0a3
- Use `ExeOOMMFRunner` on Windows
- Baseclass for `ExeOOMMFRunner` and `TclOOMMFRunner` to avoid code duplication.
- Kill OOMMF only when runner goes out of scope (on MacOS and Linux)
- [Tutorial is deleted because it fails during test and is dealt with in #70 ]

### CODE REVIEW

**Comment by lang-m** [comment]
@marijanbeg Have you got any idea why the last CI run did fail?

**Comment by marijanbeg** [comment]
No idea, Windows mysteries :/

**Comment by fangohr** [comment]
We need to think about the compatibility of this oommfc code with the OOMMF version we find. The code in this PR is written so (I think) that it will work correctly with the latest OOMMF2.0a3. 

What if that isn't installed? At least the conda version will break (because for the condo-distributed OOMMF2.0a2, not all extensions are included). Is this a problem for any other scenario?

**Comment by fangohr** [comment]
Forgot to say: apart from the point I raised just above, the PR looks good to me.

**Comment by fangohr** [comment]
> We need to think about the compatibility of this oommfc code with the OOMMF version we find. The code in this PR is written so (I think) that it will work correctly with the latest OOMMF2.0a3.
> 
> What if that isn't installed? At least the conda version will break (because for the condo-distributed OOMMF2.0a2, not all extensions are included). Is this a problem for any other scenario?

@lang-m and I discussed this. We conclude that for the condo-distributed ubermag version, this is no problem as the OOMMFC conda package that is required for Ubermag is completely fixed by the Ubermag conda package requirements. So for all users installing Ubermag and OOMMF through conda, there is for a given Ubermag package version exactly one matching and prescribed OOMMF version, and conda will automatically install the right one. We expect that the majority of users is installing Ubermag via conda, in particular in the windows world.

In addition: where we use Docker as a fall back, the Ubermag version can make sure that we use the matching OOMMF through choice of the right docker image.

We discussed that we should create a list of ubermag versions together with the matching OOMMF version as part of the documentation (starting from the next release).

We had some other ideas (such as a version_info (or similar) command and a citation() command, for which issues will be created later and outside this PR.

**Comment by marijanbeg** [comment]
I agree. We can start with this approach starting from the next version.

**Pull request merged**
