### PR TITLE
Change docker image

### PR DESCRIPTION
**Pull request by lang-m**

### CODE REVIEW

**Review by fangohr — COMMENTED** [review]
There are more occurrences of "ubermag/oommf" in the file that need updating: at least once in the documentation, and once in the code.

**Comment by lang-m** [comment]
Thanks @fangohr

**Comment by fangohr** [comment]
I don't know why we define the docker image in multiple places in the code. 

Would it be better to make it into a global variable in the module and define it only once?  (This might also allow to change it programmatically for debugging and testing purposes.)

**Comment by lang-m** [comment]
Most of the occurrences are tests that aren't used anyways. I've removed the second occurrence (when searching the default runner) where it didn't make any sense to specify it. Generally speaking, we should only need to specify it once because the correct image name is the default parameter in `DockerOOMMFRunner`. Therefore it should always be used.

**Comment by lang-m** [comment]
Testing the docker image on GitHub actions is not really feasible at the moment:
- Windows: we cannot run Linux Docker containers (https://github.com/actions/virtual-environments/issues/1143#issuecomment-651178811)
- Ubuntu: we cannot change the user inside the Docker container (https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#user)
- MacOS: Docker not available (by default) because of legal issues.

**Comment by fangohr** [comment]
Okay, thanks for trying with the tests. Looks good to me.

**Pull request merged**
