### PR TITLE
Time dependence

### PR DESCRIPTION
**Pull request by lang-m**
- unified keys
- documentation

### CODE REVIEW

**Comment by lang-m** [comment]
@marijanbeg To simplify the interface we could have only one parameter to specify a time dependence (and additional parameters for required details):
```python
# for sin/sinc
mm.Zeeman(H, tfunc='sin', f=..., t0=...)  # wave -> tfunc
# for callable
mm.Zeeman(H, tfunc=<function>, dt=...)  # time_dependence -> tfunc, tstep -> dt
```
Maybe you've got an idea for a better name. Some other ideas I have had are `tdep` and `f_t` (easy to confuse with frequency `f` though).

**Comment by lang-m** [comment]
`func`

**Comment by lang-m** [comment]
@marijanbeg Could you please have a look at the parameters for the Slonczewski current. I've added this second time-dependent current for better clarity (as we discussed). But the parameters might be unrealistic and currently do not replicate the desired behaviour.

**Comment by marijanbeg** [comment]
Looks good to me. The order of magnitude is 10-100 MA/cm2. I would just reduce P to 0.8 to make it more realistic.

**Pull request merged**
