### PR TITLE
Generalised zhang li

### PR DESCRIPTION
**Pull request by lang-m**
Support for current in arbitrary direction

### CODE REVIEW

**Comment by lang-m** [comment]
Note: this requires a custom build of OOMMF with the additional extension

**Review by swapneelap — APPROVED** [review]
Looks good to me!

**Comment by lang-m** [comment]
Re-run tests after merging ubermag/micromagneticmodel#75 and ubermag/micromagnetictests#48

**Review by samjrholt — APPROVED** [review]

**Comment by lang-m** [comment]
- [ ] Re-run CI after merging https://github.com/fangohr/oommf/pull/65

**Pull request merged**
